version: '3.5'

services:

  convid-ssh-server:
    build: .
    image: labbsr0x/convid-ssh-server
    ports:
      - "2222:22"
    environment:
      - LOG_LEVEL=debug
      - ACCOUNTS_API_URL=http://simple-file-server:4000

  simple-file-server:
    image: flaviostutz/simple-file-server
    ports:
      - "4000:4000"
    environment:
      - LOG_LEVEL=info
      - LOCATION_BASE_URL=http://localhost:4000
